export default function Head() {
  return (
    <>
      <title>
        Online Shopping Site for Mobiles, Electronics, Furniture, Grocery,
        Lifestyle, Books & More. Best Offers!
      </title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
